baseURL: "https://hhanalytics.netlify.app/"
languageCode: en-us
title: Der FUNalytics Blog
theme: hugo-theme-cactus
copyright: Christian J. · Made with the blogdown package and the Cactus theme for Hugo.
disqusShortname: example
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Beiträge
      url: /posts
      weight: 2
    - name: Über diesen Blog & mich
      url: /about
      weight: 3
markup:
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 2
params:
  colortheme: white
  comments:
    enabled: yes
    engine: disqus
  dateFormat: '2006-01-02'
  description: Hello World!
  googleAnalyticsAsync: yes
  mainSection: posts
  postsOnHomePage: 7
  projectsUrl:
  rss: yes
  show_updated: yes
  showAllPostsOnHomePage: no
  showProjectsList: yes
  showReadTime: yes
  social:
    - link: https://www.linkedin.com/in/christian-jähnert-ab427412a/
      name: linkedin
  tagsOverview: no
