baseURL: "https://hhanalytics.netlify.app/"
languageCode: en-us
title: HH analytics blog
theme: hugo-theme-cactus
copyright: You
disqusShortname: example
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Beiträge
      url: /posts
      weight: 2
    - name: Über mich
      url: /about
      weight: 3
markup:
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 2
params:
  colortheme: white
  comments:
    enabled: no
    engine: disqus
  dateFormat: '2006-01-02'
  description: Hallo! Guten Tag! Hello World!
  googleAnalyticsAsync: yes
  mainSection: posts
  postsOnHomePage: 5
  projectsUrl: https://github.com/gohugoio
  rss: yes
  show_updated: no
  showAllPostsOnHomePage: no
  showProjectsList: yes
  showReadTime: no
  social:
    - link: https://github.com/gohugoio
      name: github
    - link: https://www.linkedin.com/in/christian-jähnert-ab427412a/
      name: linkedin
    - link: example@example.com
      name: email
  tagsOverview: no
